apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}-route
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
  port:
    targetPort: "{{ .Values.ports.app }}"
  tls:
    termination: edge
