apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.ports.app }}
      targetPort: {{ .Values.ports.app }}
  selector:
    app: {{ .Values.app.name }}
